### PR TITLE
ISSUE#3: Implemented Tika Metadata

### PR DESCRIPTION
**Pull request by s4zuk3**
Hello! This is my first time contributing to a public repository, and it’s also my first time using Rust. I hope you find the changes satisfactory. I found your repository very interesting, as I use Tika a lot but I don't like having to depend on Java for its use. 

I need the metadata that Tika provides, so I made the necessary changes to implement it in this repository, trying to modify as little as possible. From what I understood of the code, the metadata was already being delivered, it just wasn't fully captured and passed through the binding, so theoretically, the performance should remain the same.

Thanks!

### CODE REVIEW

**Comment by nmammeri** [comment]
Thanks Francisco for putting the effort to make this pull request. It's big feature and will require upgrading the 0.2. I was planning to do this myself but It's great to see that you jumped on it. 

I'll need sometime to look into this. 

Is it ok if I make changes straight to your branch?

**Comment by s4zuk3** [comment]
> Thanks Francisco for putting the effort to make this pull request. It's big feature and will require upgrading the 0.2. I was planning to do this myself but It's great to see that you jumped on it.
> 
> I'll need sometime to look into this.
> 
> Is it ok if I make changes straight to your branch?


Sure, please make any necessary changes! Thank you very much!

**Comment by s4zuk3** [comment]
@nmammeri Hey! is there anything missing or can I help you with something to merge this PR?

**Comment by s4zuk3** [comment]
I will create a new updated PR.

**Pull request closed without merging**
